spring.application.name=agendamento-app
server.port=8081

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:8745/agendamento_db
spring.datasource.username=postgres
spring.datasource.password=Vrpost@Server
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
#spring.jpa.hibernate.ddl-auto=create
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Flyway (migrações)
spring.flyway.enabled=false

# Logging
logging.level.com.example.agendamento_app=DEBUG
logging.level.org.springframework.web=INFO

spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false

# JWT Configuration
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=86400000

# Spring Security
spring.security.enabled=true